DIM_CLAIMS_COLUMNS = """
  provider_id               string,
  provider_name             string,
  provider_address          string,
  provider_city             string,
  provider_state            string,
  provider_zip_code         string,

  measure_code              int,
  measure_description       string,
  resident_type             string,
  adjusted_score            double,
  observed_score            double,
  expected_score            double,
  measure_score_footnote    int,
  used_in_five_star_rating  string,
  measure_period            string,

  provider_full_address     string,
  processing_date           date,      
"""


FCT_STAFFING_LEVELS_COLUMNS = """
  provider_id             string,
  provider_name           string,
  provider_city           string,
  provider_state          string,
  provider_county_name    string,
  provider_county_fips    string,
  calendar_year_quarter   string,
  work_date               date,
  num_patients            int,

  hrs_registered_nurses                           double,
  hrs_registered_nurses_employee                  double,
  hrs_registered_nurses_contracted                double,
  hrs_registered_nurses_onduty                    double,
  hrs_registered_nurses_onduty_employed           double,
  hrs_registered_nurses_onduty_contracted         double,
  hrs_registered_nurse_admins                     double,
  hrs_registered_nurse_admins_employee            double,
  hrs_registered_nurse_admins_contracted          double,

  hrs_licensed_practical_nurse_admins             double,
  hrs_licensed_practical_nurse_admins_employee    double,
  hrs_licensed_practical_nurse_admins_contracted  double,
  hrs_licensed_practical_nurses                   double,
  hrs_licensed_practical_nurses_employee          double,
  hrs_licensed_practical_nurses_contracted        double,

  hrs_certified_nursing_assistants                double,
  hrs_certified_nursing_assistants_employee       double,
  hrs_certified_nursing_assistants_contracted     double,
  hrs_nursing_assistant_trainees                  double,
  hrs_nursing_assistant_trainees_employee         double,
  hrs_nursing_assistant_trainees_contracted       double,

  hrs_medication_aides                            double,
  hrs_medication_aides_employee                   double,
  hrs_medication_aides_contracted                 double,
"""


DIM_PROVIDERS_COLUMNS = """
  provider_id                                  string,
  provider_name                                string,
  provider_address                             string,
  provider_city                                string,
  provider_state                               string,
  provider_zip_code                            string,
  provider_phone_number                        string,
  provider_ssa_county_code                     string,
  provider_county_name                         string,
  ownership_type                               string,
  num_certified_beds                           int,
  avg_residents_per_day                        double,
  avg_residents_per_day_footnote               int,
  provider_type                                string,
  provider_in_hospital_flag                    string,
  legal_business_name                          string,
  first_approved_date                          date,
  affiliated_entity_name                       string,
  affiliated_entity_id                         string,
  ccrc_flag                                    string,
  special_focus_status                         string,
  abuse_icon_flag                              string,
  health_inspection_gt2yrs_flag                string,
  ownership_change_12mo_flag                   string,
  resident_family_council                      string,
  sprinkler_all_required_areas                 string,

  overall_rating                               int,
  overall_rating_footnote                      int,
  health_inspection_rating                     int,
  health_inspection_rating_footnote            int,
  qm_rating                                    int,
  qm_rating_footnote                           int,
  long_stay_qm_rating                          int,
  long_stay_qm_rating_footnote                 int,
  short_stay_qm_rating                         int,
  short_stay_qm_rating_footnote                int,
  staffing_rating                              int,
  staffing_rating_footnote                     int,
  reported_staffing_footnote                   int,
  pt_staffing_footnote                         int,

  reported_aide_hrs_resday                      double,
  reported_lpn_hrs_resday                       double,
  reported_rn_hrs_resday                        double,
  reported_licensed_hrs_resday                  double,
  reported_total_nurse_hrs_resday               double,
  reported_weekend_total_nurse_hrs_resday       double,
  reported_weekend_rn_hrs_resday                double,
  reported_pt_hrs_resday                        double,

  total_nurse_turnover                          double,
  total_nurse_turnover_footnote                 int,
  rn_turnover                                   double,
  rn_turnover_footnote                          int,
  administrator_turnover_count                  int,
  administrator_turnover_footnote               int,

  nursing_case_mix_index                        double,
  nursing_case_mix_index_ratio                  double,
  case_mix_aide_hrs_resday                      double,
  case_mix_lpn_hrs_resday                       double,
  case_mix_rn_hrs_resday                        double,
  case_mix_total_nurse_hrs_resday               double,
  case_mix_weekend_total_nurse_hrs_resday       double,
  adjusted_aide_hrs_resday                      double,
  adjusted_lpn_hrs_resday                       double,
  adjusted_rn_hrs_resday                        double,
  adjusted_total_nurse_hrs_resday               double,
  adjusted_weekend_total_nurse_hrs_resday       double,

  rating_cycle1_standard_survey_date            string,
  rating_cycle1_total_health_deficiencies       int,
  rating_cycle1_standard_health_deficiencies    int,
  rating_cycle1_complaint_health_deficiencies   int,
  rating_cycle1_health_deficiency_score         int,
  rating_cycle1_health_revisits                 int,
  rating_cycle1_health_revisit_score            int,
  rating_cycle1_total_health_score              int,

  rating_cycle2_standard_survey_date            string,
  rating_cycle2_total_health_deficiencies       int,
  rating_cycle2_standard_health_deficiencies    int,
  rating_cycle2_complaint_health_deficiencies   int,
  rating_cycle2_health_deficiency_score         int,
  rating_cycle2_health_revisits                 int,
  rating_cycle2_health_revisit_score            int,
  rating_cycle2_total_health_score              int,

  rating_cycle3_standard_survey_date            string,
  rating_cycle3_total_health_deficiencies       int,
  rating_cycle3_standard_health_deficiencies    int,
  rating_cycle3_complaint_health_deficiencies   int,
  rating_cycle3_health_deficiency_score         int,
  rating_cycle3_health_revisits                 int,
  rating_cycle3_health_revisit_score            int,
  rating_cycle3_total_health_score              int,

  total_weighted_health_survey_score            double,
  facility_reported_incidents                   int,
  substantiated_complaints                      int,
  infection_control_citations                   int,
  fines_count                                   int,
  fines_total_dollars                           double,
  payment_denials_count                         int,
  total_penalties_count                         int,

  provider_full_address                         string,
  provider_latitude                             double,
  provider_longitude                            double,
  geocoding_footnote                            int,
  processing_date                               date,
"""

DIM_DATES_COLUMNS = """
  date              DATE,
  date_key          INT,
  year              INT,
  cy_quarter        STRING,
  month             INT,
  month_name        STRING,
  day               INT,
  week_of_year      INT,
  day_of_week       INT,
  day_of_week_name  STRING,
  is_weekday        BOOLEAN,
"""


DAILY_STAFFING_RAW_COLUMNS = """
  PROVNUM          string,
  PROVNAME         string,
  CITY             string,
  STATE            string,
  COUNTY_NAME      string,
  COUNTY_FIPS      string,
  CY_Qtr           string,
  WorkDate         string,
  MDScensus        string,
  Hrs_RNDON        string,
  Hrs_RNDON_emp    string,
  Hrs_RNDON_ctr    string,
  Hrs_RNadmin      string,
  Hrs_RNadmin_emp  string,
  Hrs_RNadmin_ctr  string,
  Hrs_RN           string,
  Hrs_RN_emp       string,
  Hrs_RN_ctr       string,
  Hrs_LPNadmin     string,
  Hrs_LPNadmin_emp string,
  Hrs_LPNadmin_ctr string,
  Hrs_LPN          string,
  Hrs_LPN_emp      string,
  Hrs_LPN_ctr      string,
  Hrs_CNA          string,
  Hrs_CNA_emp      string,
  Hrs_CNA_ctr      string,
  Hrs_NAtrn        string,
  Hrs_NAtrn_emp    string,
  Hrs_NAtrn_ctr    string,
  Hrs_MedAide      string,
  Hrs_MedAide_emp  string,
  Hrs_MedAide_ctr  string,
"""


PROVIDERS_RAW_COLUMNS = """
  `CMS Certification Number (CCN)` string,
  `Provider Name` string,
  `Provider Address` string,
  `City/Town` string,
  `State` string,
  `ZIP Code` string,
  `Telephone Number` string,
  `Provider SSA County Code` string,
  `County/Parish` string,
  `Ownership Type` string,
  `Number of Certified Beds` string,
  `Average Number of Residents per Day` string,
  `Average Number of Residents per Day Footnote` string,
  `Provider Type` string,
  `Provider Resides in Hospital` string,
  `Legal Business Name` string,
  `Date First Approved to Provide Medicare and Medicaid Services` string,
  `Affiliated Entity Name` string,
  `Affiliated Entity ID` string,
  `Continuing Care Retirement Community` string,
  `Special Focus Status` string,
  `Abuse Icon` string,
  `Most Recent Health Inspection More Than 2 Years Ago` string,
  `Provider Changed Ownership in Last 12 Months` string,
  `With a Resident and Family Council` string,
  `Automatic Sprinkler Systems in All Required Areas` string,
  `Overall Rating` string,
  `Overall Rating Footnote` string,
  `Health Inspection Rating` string,
  `Health Inspection Rating Footnote` string,
  `QM Rating` string,
  `QM Rating Footnote` string,
  `Long-Stay QM Rating` string,
  `Long-Stay QM Rating Footnote` string,
  `Short-Stay QM Rating` string,
  `Short-Stay QM Rating Footnote` string,
  `Staffing Rating` string,
  `Staffing Rating Footnote` string,
  `Reported Staffing Footnote` string,
  `Physical Therapist Staffing Footnote` string,
  `Reported Nurse Aide Staffing Hours per Resident per Day` string,
  `Reported LPN Staffing Hours per Resident per Day` string,
  `Reported RN Staffing Hours per Resident per Day` string,
  `Reported Licensed Staffing Hours per Resident per Day` string,
  `Reported Total Nurse Staffing Hours per Resident per Day` string,
  `Total number of nurse staff hours per resident per day on the weekend` string,
  `Registered Nurse hours per resident per day on the weekend` string,
  `Reported Physical Therapist Staffing Hours per Resident Per Day` string,
  `Total nursing staff turnover` string,
  `Total nursing staff turnover footnote` string,
  `Registered Nurse turnover` string,
  `Registered Nurse turnover footnote` string,
  `Number of administrators who have left the nursing home` string,
  `Administrator turnover footnote` string,
  `Nursing Case-Mix Index` string,
  `Nursing Case-Mix Index Ratio` string,
  `Case-Mix Nurse Aide Staffing Hours per Resident per Day` string,
  `Case-Mix LPN Staffing Hours per Resident per Day` string,
  `Case-Mix RN Staffing Hours per Resident per Day` string,
  `Case-Mix Total Nurse Staffing Hours per Resident per Day` string,
  `Case-Mix Weekend Total Nurse Staffing Hours per Resident per Day` string,
  `Adjusted Nurse Aide Staffing Hours per Resident per Day` string,
  `Adjusted LPN Staffing Hours per Resident per Day` string,
  `Adjusted RN Staffing Hours per Resident per Day` string,
  `Adjusted Total Nurse Staffing Hours per Resident per Day` string,
  `Adjusted Weekend Total Nurse Staffing Hours per Resident per Day` string,
  `Rating Cycle 1 Standard Survey Health Date` string,
  `Rating Cycle 1 Total Number of Health Deficiencies` string,
  `Rating Cycle 1 Number of Standard Health Deficiencies` string,
  `Rating Cycle 1 Number of Complaint Health Deficiencies` string,
  `Rating Cycle 1 Health Deficiency Score` string,
  `Rating Cycle 1 Number of Health Revisits` string,
  `Rating Cycle 1 Health Revisit Score` string,
  `Rating Cycle 1 Total Health Score` string,
  `Rating Cycle 2 Standard Health Survey Date` string,
  `Rating Cycle 2 Total Number of Health Deficiencies` string,
  `Rating Cycle 2 Number of Standard Health Deficiencies` string,
  `Rating Cycle 2 Number of Complaint Health Deficiencies` string,
  `Rating Cycle 2 Health Deficiency Score` string,
  `Rating Cycle 2 Number of Health Revisits` string,
  `Rating Cycle 2 Health Revisit Score` string,
  `Rating Cycle 2 Total Health Score` string,
  `Rating Cycle 3 Standard Health Survey Date` string,
  `Rating Cycle 3 Total Number of Health Deficiencies` string,
  `Rating Cycle 3 Number of Standard Health Deficiencies` string,
  `Rating Cycle 3 Number of Complaint Health Deficiencies` string,
  `Rating Cycle 3 Health Deficiency Score` string,
  `Rating Cycle 3 Number of Health Revisits` string,
  `Rating Cycle 3 Health Revisit Score` string,
  `Rating Cycle 3 Total Health Score` string,
  `Total Weighted Health Survey Score` string,
  `Number of Facility Reported Incidents` string,
  `Number of Substantiated Complaints` string,
  `Number of Citations from Infection Control Inspections` string,
  `Number of Fines` string,
  `Total Amount of Fines in Dollars` string,
  `Number of Payment Denials` string,
  `Total Number of Penalties` string,
  `Location` string,
  `Latitude` string,
  `Longitude` string,
  `Geocoding Footnote` string,
  `Processing Date` string,
"""


CLAIMS_RAW_COLUMNS = """
  `CMS Certification Number (CCN)` string,
  `Provider Name` string,
  `Provider Address` string,
  `City/Town` string,
  `State` string,
  `ZIP Code` string,
  `Measure Code` string,
  `Measure Description` string,
  `Resident type` string,
  `Adjusted Score` string,
  `Observed Score` string,
  `Expected Score` string,
  `Footnote for Score` string,
  `Used in Quality Measure Five Star Rating` string,
  `Measure Period` string,
  `Location` string,
  `Processing Date` string,
"""


BRONZE_COLUMNS = {
  "daily_staffing_raw": DAILY_STAFFING_RAW_COLUMNS,
  "providers_raw": PROVIDERS_RAW_COLUMNS,
  "claims_raw": CLAIMS_RAW_COLUMNS
}
SILVER_COLUMNS = {
  "fct_staffing_levels": FCT_STAFFING_LEVELS_COLUMNS,
  "dim_providers": DIM_PROVIDERS_COLUMNS,
  "dim_claims": DIM_CLAIMS_COLUMNS,
  "dim_dates": DIM_DATES_COLUMNS
}
